spring:
  datasource:
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/dbname
    username: your db username
    password: your db password
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 10
    connection-test-query: SELECT 1;
    connection-timeout: 30000
    max-lifetime: 1800000
    validation-timeout: 10000
    idle-timeout: 10000

server:
      address: 127.0.0.1
      port: 8080

logging:
      level:
        org.springframework.web: ERROR
        org.springframework: ERROR
        org.mybatis.spring: ERROR
        org.apache.ibatis: ERROR